version: "3"

networks:
  api-network:
    driver: bridge

services:
  api:
    build: ./remi-assess-backend
    ports:
      - "3000:3000"
    env_file:
      - ./remi-assess-backend/.env
    environment:
      DB_HOST: postgres
    networks:
      - api-network
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./remi-assess-backend:/app/remi-assess-backend
      - /app/remi-assess-backend/node_modules
    restart: always

  front-end:
    build: ./remi-assess-frontend
    ports:
      - "8000:8000"
    env_file:
      - ./remi-assess-frontend/.env
    volumes:
      - ./remi-assess-frontend:/app/remi-assess-frontend
      - /app/remi-assess-frontend/node_modules
    restart: always

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - "5433:5432"
    # May give error on windows
    networks:
      - api-network
    volumes:
      - ./db-data/postgresql:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    env_file:
      - ./remi-assess-backend/.env

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - api-network
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
